name: Deploy HTML to EC2
on: 
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Show all files
      run: ls -al
    - name: Copy files via ssh
      uses: appleboy/scp-action@v1
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        Key: ${{ secrets.EC2_SSH }}
        port: 22
        source: "./index.html"
        target: "/home/${{ secrets.EC2_USERNAME }}/tmp"

    - name: Move file to /var/www/html with sudo
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH }}
        script: |
            sudo mkdir -p /var/www/html
            sudo mv /home/${{ secrets.EC2_USERNAME }}/tmp/index.html /var/www/html/index.html
            sudo chown www-data:www-data /var/www/html/index.html

          
            
